services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/partner
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partner
    ports:
      - 3306:3306
